In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

# Create & Read

#### 1D Array

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1 

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int32')

In [10]:
arr1.ndim # Pour savoir la dimension d'un tableau 

1

In [11]:
arr1.size

5

#### 2D Array

In [13]:
arr2 = np.array([[1,5,6], [2,7,9]])
arr2

array([[1, 5, 6],
       [2, 7, 9]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape # (row, col)

(2, 3)

In [16]:
arr2.dtype

dtype('int32')

In [17]:
arr2.size

6

#### 3D Array 

In [25]:
arr3 = np.array([[[1,5,6], [2,7,9]], [[5, 4, 8], [7, 2, 3]], [[0, 4, 3], [5, 0, 3]]])
arr3

array([[[1, 5, 6],
        [2, 7, 9]],

       [[5, 4, 8],
        [7, 2, 3]],

       [[0, 4, 3],
        [5, 0, 3]]])

In [26]:
arr3.ndim

3

In [27]:
arr3.shape

(3, 2, 3)

### Create Random Array

In [28]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.89865058, 0.45832145, 0.32514469],
        [0.37411927, 0.16790704, 0.48414522]],

       [[0.10621291, 0.15444916, 0.55899427],
        [0.49191653, 0.67018133, 0.03537769]],

       [[0.59987586, 0.46790002, 0.30240251],
        [0.97247035, 0.57071615, 0.9133842 ]]])

In [29]:
randomArr.dtype

dtype('float64')

In [32]:
zeros = np.zeros((3, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
zeros.ndim

3

In [34]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [36]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
arr3

array([[[1, 5, 6],
        [2, 7, 9]],

       [[5, 4, 8],
        [7, 2, 3]],

       [[0, 4, 3],
        [5, 0, 3]]])

In [38]:
arr3[0]

array([[1, 5, 6],
       [2, 7, 9]])

In [39]:
arr3[0][0]

array([1, 5, 6])

In [40]:
arr3[0:2]

array([[[1, 5, 6],
        [2, 7, 9]],

       [[5, 4, 8],
        [7, 2, 3]]])

In [41]:
arr3[0:3]

array([[[1, 5, 6],
        [2, 7, 9]],

       [[5, 4, 8],
        [7, 2, 3]],

       [[0, 4, 3],
        [5, 0, 3]]])

In [43]:
arr3[:-1]

array([[[1, 5, 6],
        [2, 7, 9]],

       [[5, 4, 8],
        [7, 2, 3]]])

In [46]:
arr3[1, 0, 1]

4

### Update & Delete

In [47]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [48]:
a1

array([[[0.0854257 , 0.98236779],
        [0.76846731, 0.79451212],
        [0.09380726, 0.67016809]],

       [[0.56460588, 0.46398105],
        [0.07259747, 0.39535103],
        [0.62601672, 0.19811497]]])

In [49]:
a2

array([[[0.76864047, 0.2288722 ],
        [0.27547079, 0.6078035 ],
        [0.12979697, 0.66832151]],

       [[0.35141135, 0.7766174 ],
        [0.70503144, 0.48049723],
        [0.37411196, 0.80538075]]])

### Basic Math Operations

In [50]:
np.add(a1, a2)

array([[[0.85406616, 1.21123998],
        [1.0439381 , 1.40231562],
        [0.22360422, 1.3384896 ]],

       [[0.91601723, 1.24059845],
        [0.7776289 , 0.87584826],
        [1.00012868, 1.00349572]]])

In [51]:
np.subtract(a1, a2)

array([[[-0.68321477,  0.75349559],
        [ 0.49299651,  0.18670862],
        [-0.03598971,  0.00184659]],

       [[ 0.21319454, -0.31263634],
        [-0.63243397, -0.0851462 ],
        [ 0.25190476, -0.60726579]]])

In [52]:
np.divide(a1, a2)

array([[[0.11113869, 4.29221112],
        [2.78965076, 1.30718582],
        [0.72272303, 1.00276302]],

       [[1.60668086, 0.5974384 ],
        [0.10297054, 0.82279564],
        [1.67334058, 0.2459892 ]]])

### Statistical operations

In [53]:
sqrt_value = np.sqrt(25)
abs_value = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [54]:
arr3

array([[[1, 5, 6],
        [2, 7, 9]],

       [[5, 4, 8],
        [7, 2, 3]],

       [[0, 4, 3],
        [5, 0, 3]]])

In [55]:
arr3[0, 0, 2] = 500
arr3

array([[[  1,   5, 500],
        [  2,   7,   9]],

       [[  5,   4,   8],
        [  7,   2,   3]],

       [[  0,   4,   3],
        [  5,   0,   3]]])

In [56]:
arr3.sort
arr3

array([[[  1,   5, 500],
        [  2,   7,   9]],

       [[  5,   4,   8],
        [  7,   2,   3]],

       [[  0,   4,   3],
        [  5,   0,   3]]])

In [57]:
# Reshape
arr3.shape

(3, 2, 3)

In [59]:
arr3_reshape = arr3.reshape([2, 3, 3])
arr3_reshape

array([[[  1,   5, 500],
        [  2,   7,   9],
        [  5,   4,   8]],

       [[  7,   2,   3],
        [  0,   4,   3],
        [  5,   0,   3]]])

#### Appending & Inserting

In [60]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [61]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [62]:
appd = np.append(zeros, new_array, axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [64]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [65]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [66]:
inserted_array = np.insert(zeros, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete 

In [67]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.70595909, 0.17168269, 0.04672232],
        [0.70723418, 0.55272702, 0.18686179]],

       [[0.06363449, 0.69231787, 0.43014185],
        [0.90440883, 0.27860885, 0.43602633]],

       [[0.62610959, 0.05042095, 0.31711774],
        [0.49460443, 0.79223644, 0.06624559]]])

In [72]:
# Delete the array
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.70723418, 0.55272702, 0.18686179]],

       [[0.90440883, 0.27860885, 0.43602633]],

       [[0.49460443, 0.79223644, 0.06624559]]])

In [73]:
np.save("new_array", arr5)

In [75]:
np.load("new_array.npy")

array([[[0.70723418, 0.55272702, 0.18686179]],

       [[0.90440883, 0.27860885, 0.43602633]],

       [[0.49460443, 0.79223644, 0.06624559]]])